describe("findSpaceship", function() {
    it("should return [7, 2] for the given example map", function() {
        const map = `
..........
..........
..........
.......X..
..........
..........`;
        expect(findSpaceship(map)).toEqual([7, 2]);
    });
});
