describe("findSpaceship", function() {
    it("should return [7, 2] for the given example map", function() {
        const map = `
..........
..........
..........
.......X..
..........
..........`;
        expect(findSpaceship(map)).toEqual([7, 2]);
    });
    it("should return 'Spaceship lost forever.' if the spaceship is not found", function() {
        const map = `
..........
..........
..........
..........
..........
..........`;
        expect(findSpaceship(map)).toBe("Spaceship lost forever.");
    });
});
